export const GAME_WIDTH = 1920;
export const GAME_HEIGHT = 1080;

export const COLORS = {
    PRIMARY: 0x00ffcc,
    SECONDARY: 0xff6b35,
    DANGER: 0xff3366,
    WARNING: 0xffcc00,
    SUCCESS: 0x33ff66,
    SHIELD: 0x3399ff,
    XP: 0xcc66ff,
    BACKGROUND: 0x0a0a1a,
    UI_BG: 0x1a1a2e,
    UI_BORDER: 0x16213e,
    TEXT: 0xffffff,
    TEXT_DIM: 0x888899,
};

export const PLAYER = {
    BASE_SPEED: 420,
    BASE_HEALTH: 120,
    BASE_SHIELD: 60,
    INVULNERABLE_TIME: 1200,
    DASH_SPEED: 900,
    DASH_DURATION: 250,
    DASH_COOLDOWN: 1800,
};

export const WEAPONS = {
    LASER: {
        name: 'Pulse Laser',
        damage: 15,
        fireRate: 200,
        speed: 900,
        color: 0x00ffcc,
        size: { width: 4, height: 20 },
        sound: 'laser1',
        spread: 0,
        projectiles: 1,
    },
    PLASMA: {
        name: 'Plasma Cannon',
        damage: 35,
        fireRate: 500,
        speed: 700,
        color: 0xff6b35,
        size: { width: 8, height: 8 },
        sound: 'plasma1',
        spread: 0,
        projectiles: 1,
    },
    SPREAD: {
        name: 'Spread Shot',
        damage: 10,
        fireRate: 300,
        speed: 800,
        color: 0xffcc00,
        size: { width: 3, height: 15 },
        sound: 'laser2',
        spread: 15,
        projectiles: 3,
    },
    MISSILE: {
        name: 'Homing Missiles',
        damage: 50,
        fireRate: 800,
        speed: 500,
        color: 0xff3366,
        size: { width: 6, height: 12 },
        sound: 'missile1',
        spread: 0,
        projectiles: 2,
        homing: true,
    },
    BEAM: {
        name: 'Ion Beam',
        damage: 5,
        fireRate: 50,
        speed: 1500,
        color: 0x3399ff,
        size: { width: 3, height: 30 },
        sound: 'beam1',
        spread: 0,
        projectiles: 1,
        piercing: true,
    },
};

export const ENEMIES = {
    DRONE: {
        name: 'Scout Drone',
        health: 30,
        speed: 140,
        damage: 8,
        score: 100,
        color: 0xff3366,
        size: 20,
        behavior: 'chase',
        fireRate: 0,
    },
    FIGHTER: {
        name: 'Fighter',
        health: 55,
        speed: 180,
        damage: 12,
        score: 200,
        color: 0xff6b35,
        size: 25,
        behavior: 'strafe',
        fireRate: 1800,
    },
    BOMBER: {
        name: 'Bomber',
        health: 100,
        speed: 100,
        damage: 30,
        score: 300,
        color: 0xffcc00,
        size: 35,
        behavior: 'bomb',
        fireRate: 2000,
    },
    SNIPER: {
        name: 'Sniper',
        health: 40,
        speed: 80,
        damage: 40,
        score: 250,
        color: 0xcc66ff,
        size: 22,
        behavior: 'snipe',
        fireRate: 2500,
    },
    TANK: {
        name: 'Heavy Tank',
        health: 200,
        speed: 60,
        damage: 25,
        score: 400,
        color: 0x666699,
        size: 40,
        behavior: 'tank',
        fireRate: 1800,
    },
    SWARM: {
        name: 'Swarm Unit',
        health: 15,
        speed: 250,
        damage: 5,
        score: 50,
        color: 0x33ff66,
        size: 12,
        behavior: 'swarm',
        fireRate: 0,
    },
};

export const BOSSES = {
    MOTHERSHIP: {
        name: 'Void Mothership',
        health: 2000,
        speed: 50,
        damage: 30,
        score: 5000,
        color: 0xff0066,
        size: 120,
        phases: 3,
    },
    DESTROYER: {
        name: 'Star Destroyer',
        health: 3000,
        speed: 40,
        damage: 40,
        score: 8000,
        color: 0xff3300,
        size: 150,
        phases: 4,
    },
    HIVEMIND: {
        name: 'The Hivemind',
        health: 2500,
        speed: 60,
        damage: 25,
        score: 6000,
        color: 0x9900ff,
        size: 100,
        phases: 3,
    },
};

export const UPGRADES = {
    DAMAGE: { name: 'Weapon Damage', icon: '⚔️', maxLevel: 10, costBase: 100, costScale: 1.5 },
    FIRE_RATE: { name: 'Fire Rate', icon: '🔥', maxLevel: 10, costBase: 100, costScale: 1.5 },
    SPEED: { name: 'Ship Speed', icon: '💨', maxLevel: 8, costBase: 150, costScale: 1.4 },
    HEALTH: { name: 'Max Health', icon: '❤️', maxLevel: 10, costBase: 120, costScale: 1.5 },
    SHIELD: { name: 'Max Shield', icon: '🛡️', maxLevel: 8, costBase: 130, costScale: 1.6 },
    SHIELD_REGEN: { name: 'Shield Regen', icon: '✨', maxLevel: 6, costBase: 200, costScale: 1.7 },
    DASH: { name: 'Dash Cooldown', icon: '⚡', maxLevel: 5, costBase: 250, costScale: 1.8 },
    MAGNET: { name: 'Pickup Range', icon: '🧲', maxLevel: 5, costBase: 100, costScale: 1.3 },
    LUCK: { name: 'Drop Luck', icon: '🍀', maxLevel: 5, costBase: 180, costScale: 1.6 },
    CRIT: { name: 'Crit Chance', icon: '💥', maxLevel: 8, costBase: 150, costScale: 1.5 },
};

export const WAVES = {
    ENEMIES_PER_WAVE_BASE: 5,
    ENEMIES_PER_WAVE_SCALE: 2,
    WAVE_DELAY: 3000,
    BOSS_EVERY: 5,
    DIFFICULTY_SCALE: 0.15,
};

export const PARTICLES = {
    EXPLOSION_COUNT: 30,
    TRAIL_FREQUENCY: 50,
    HIT_COUNT: 8,
    PICKUP_COUNT: 12,
};

export const PICKUPS = {
    HEALTH: { name: 'Health', color: 0x33ff66, value: 20 },
    SHIELD: { name: 'Shield', color: 0x3399ff, value: 25 },
    XP: { name: 'Experience', color: 0xcc66ff, value: 10 },
    CURRENCY: { name: 'Credits', color: 0xffcc00, value: 5 },
    WEAPON: { name: 'Weapon Power', color: 0xff6b35, value: 1 },
};
